# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# ESLint is a tool for identifying and reporting on patterns
# found in ECMAScript/JavaScript code.
# More details at https://github.com/eslint/eslint
# and https://eslint.org

name: ESLint
on:
  workflow_dispatch:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
    paths:
      - './frontend/**'

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies with Bun
        run: bun install

      - name: Run ESLint
        run: |
          bunx eslint . --config eslint.config.ts
